# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    MONGO_URI_LOCAL: ${{secrets.MONGO_URI_LOCAL}}
    JWT_SECRET: ${{secrets.JWT_SECRET_LOCAL}}
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image-api-arkademy
    - name: Remove dangling image
      run: docker image prune -f
    - name: Restart docker container
      run: | 
        docker stop container-api-arkademy || true
        docker run --rm -d -p 8080:8080 \
        -e MONGO_URI_LOCAL=${MONGO_URI_LOCAL} \
        -e JWT_SECRET=${JWT_SECRET} \
        --name container-api-arkademy image-api-arkademy