# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir -p ./dist
        go build -o ./dist/
    - name: Env
      run: |
        touch .env
        echo MONGO_URI_LOCAL=${{ secrets.MONGO_URI_LOCAL }} >> .env
        echo JWT_SECRET_LOCAL=${{secrets.JWT_SECRET_LOCAL}} >> .env
        cat .env
    - name: Run
      run: |
        killall api-arkademy || true
        ./dist/api-arkademy