# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "cicd","main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Login into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      env:
        MONGO_URI_LOCAL: ${{secrets.MONGO_URI_LOCAL}}
        JWT_SECRET: ${{secrets.JWT_SECRET_LOCAL}}
      run: docker build . --file Dockerfile --tag image-api-arkademy
    - name: Remove dangling image
      run: docker image prune -f
    - name: Restart docker container
      run: | 
        docker stop container-api-arkademy || true
        docker run -d -p 8080:8080 --rm --name container-api-arkademy image-api-arkademy